### PR TITLE
Some fixes and improvements

### PR DESCRIPTION
**Pull request by papampi**
Some changes in install script 
1- Handle git installation
2- Better check for user and user home
3- Some changes to handle newer pip installations limits
4- Better system service to limit retry and start after network

### CODE REVIEW

**Comment by bonelifer** [comment]
Also handling non Volumio/Moode installations would be awesome.

**Comment by papampi** [comment]
> Also handling non Volumio/Moode installations would be awesome.

These changes installs mpd2chromecast with any user no matter if its moode/volumio or not.
Dont know if it can run on OS other than Debian base or not.

**Comment by papampi** [comment]
> Also handling non Volumio/Moode installations would be awesome.

Try my fork with these changes and let me know:
`curl -s https://raw.githubusercontent.com/papampi/mpd2chromecast/master/install.sh | sudo bash
`

**Comment by dresdner353** [comment]
Updated main branch now with changes to address the issues. I incorporated your approach of accessing the SUDO_USER but removed the cron changes (legacy not needed any longer) and handled git and other packages with apt instead of pip. I've had similar issues on another project with this and it seems the rpi way now is to install apt packages for python modules. Luckily all we need are there and it will not risk mesing up the image if we let pip break things.

**Pull request closed without merging**
